notifications:
  email:
    recipients:
      - ahmed.elbendary@ocucon.com
  on_success: always # default: change
  on_failure: always # default: always

arch:
- amd64

language: generic

# env:
# - IMGNAME=ahmedbendo/slim-buster:${TRAVIS_BRANCH}-${TRAVIS_COMMIT:0:6}
# - IMGNAME=ahmedbendo/slim-buster:${TRAVIS_BRANCH}-R2.0.0

jobs:
  include:
    - # require the branch name to be prod
      if: branch =~ /release/i
      env: IMGNAME=ahmedbendo/slim-buster:prod-${TRAVIS_BRANCH}
      env: ns= prod
    - # require the branch name to be dev
      if: branch =~ /feature|hotfix/i
      env: IMGNAME=ahmedbendo/slim-buster:dev-${TRAVIS_COMMIT:0:6}
      env: ns= dev

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host ${IPADDR}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key ${user}@${IPADDR} pwd
- echo my github/travis commit ${TRAVIS_COMMIT}
- echo ${ns} ${IMGNAME}
# - docker image build -t ${IMGNAME} .
# - docker login -u ${DHUB_USERNAME} -p ${DHUB_PASS}
# - docker push ${IMGNAME}

script:
- dig +short myip.opendns.com @resolver1.opendns.com


after_success:
- ssh -i ./deploy_key ${user}@${IPADDR} ls -lha /home/ubuntu/.ssh
#- ssh -i ./deploy_key ${user}@${IPADDR} "kubectl set image -n ${TRAVIS_BRANCH} deployment.v1.apps/flask-travis-${TRAVIS_BRANCH}  '*=${IMGNAME}' --record=true"

